title: norGhost
iconURL: assets/logo.png
# theme: jekyll-theme-leaf

# for a clean URL
permalink: :slug

social:
 # twitter: _SupunKavinda
  github: norGhost

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 14
google_analytics: UA-NNNNNNNN-N
