title: norGhost
iconURL: https://avatars.githubusercontent.com/u/204608455?s=400&u=5840f81525d670f2ae89c2df4aebfeead952f96a&v=4 # assets/default-icon.png
# theme: jekyll-theme-leaf

# for a clean URL
permalink: :slug

social:
 # twitter: _SupunKavinda
  github: norGhost

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 14
google_analytics: UA-NNNNNNNN-N
